### ISSUE TITLE
Cache does not get removed after restart

### ISSUE THREAD

**Issue by rubenvt** [zebradog/kiosk#104]
After checking the delete cache checkbox and restarting, the cache does not seem to get deleted.

When we do this manually, we need to go to %AppData%\Local\Google\Chrome\User Data\Profile 1\Cache and remove all content inside the Cache folder.
Running on windows 7 Pro with latest chrome 50.X

What cache gets deleted using the "delete cache after restart checkbox"? perhaps possible to let it remove all content inside the Cache folder?

**Comment by kstangel** [comment]
@rubenvt we are looking into this. We've had mixed results when it comes to caching. We will keep you posted.

**Comment by kstangel** [comment]
Just debugging through this - it appears resetcache is never true and therefore we never clear the cache. Every time I navigate back to the admin page it's always unchecked.

https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L134
https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L226

**Comment by kstangel** [comment]
Nevermind it appears to remove the variable after the first time:

https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L227

**Comment by kstangel** [comment]
It seems like there is a bug with clearData or it doesn't do what we want.

See the following details : http://stackoverflow.com/questions/33022942/webview-wont-delete-cookies-storage-even-after-cleardata-no-persist-value-and

A workaround is to generate a new partition ID when "delete cache after restart" is checked.

> When the session should be ended I can generate a new unique partition ID and use that to start a new webview that will not have access to the cache of the previous one.
>
