### ISSUE TITLE
Remote admin not working on some version of chromeOS

### ISSUE THREAD

**Issue by cnicolas-maf** [zebradog/kiosk#108]
Hello,

We are testing the application on ACER chromebox CXI2-2JKM.
They connect fine to the web server .
The problem is with the remote admin, it doesn't work on all the boxes.
What we found is that some boxes have a version 42 ... of chromeOS, these one are not working,
some have version 49 ... and these are working.
Can somebody confirm this ?
Being on a closed network it is a little difficult to update all the boxes as there is no access to internet

Thank you

**Comment by matt-cook** [comment]
There was a ChromeOS bug up to v44 (I believe) that blocked remote administration: https://github.com/zebradog/kiosk/issues/14
