### ISSUE TITLE
how do I paste a content URL?

### ISSUE THREAD

**Issue by ozob3999** [zebradog/kiosk#113]
Got everything to work while running a google slide presentation; this is Awesome!  I have my display and chromebit connected to a powered timer.  It all starts automatically and there's no issues.  Thank you very much for this great software!!!

How do I copy and paste the long url for my presentation when switching to kiosk mode from the system mode?  My current solution is creating a tinyurl I remember, but I thought you may know a better way.

Thanks!

- Leonard

**Comment by matt-cook** [comment]
You currently cannot paste content into kiosk mode. This type of configuration will eventually be handled by: https://github.com/zebradog/kiosk/issues/37
