### ISSUE TITLE
Issue with the New Presenter Popup ? (Google slides)

### ISSUE THREAD

**Issue by armaal** [zebradog/kiosk#123]
Source from this board : https://goo.gl/3NKqiQ

> " We are using chromeboxes and chrome sign builder to present some content on TV's, and today we are having problems with the "Try the new Presenter view" blue popup constantly coming up.
> 
> The "Got It" option has been clicked, but next time the slideshow loads - the popup comes back.
> 
> It would be very helpful to have the options when publishing slides to a device that does not require human interaction, that these options are suppressed from appearing "

Screenshoot : http://imgur.com/srgP27v

Does anybody got a solution to disable this pop-up? I think there are something with Google Creditential. I hope this will be not persistant (I'm sure this will not)

**Comment by matt-cook** [comment]
This issues queue is specifically for the Kiosk app, not content-related issues (Google Slides in this case). The discussion would be best suited for the forum you link to above.
