### ISSUE TITLE
Option for local administration

### ISSUE THREAD

**Issue by thx1200** [zebradog/kiosk#15]
As mentioned in another support ticket, remote administration isn't possible on a ChromeBook or ChromeBox without going into developer mode.  I'd like to request a local administration optional feature.  I have five ChromeBoxes running a single page as a form of digital signage.  Right now if I want to change the URL, I have to uninstall kiosk and reinstall it, then reenable it for kiosk mode.  It's a bit of a pain, especially if I fat-finger the URL!  Worrying about users browsers to other pages isn't an issue for me because my monitors do not have keyboards or mice accessible to users.  So this is truly only when I need to perform maintenance.

So what I'm requesting basically is something like this.
- A setting in the settings screen that is a checkbox for "enable settings shortcut"
- When enabled, press CTRL+S (or something) to enter settings mode where you can change the URL and other configuration settings

**Comment by matt-cook** [comment]
@thx1200 ability to use local admin has just been added in version 5.3.0.

**Comment by tickmc** [comment]
Matt,

Could you provide details as to how this is to be used, please?

Cheers,

- Mike

**Comment by matt-cook** [comment]
If you had the option checked at setup, you'll press 'ctrl+a' to display
the login prompt and enter your username and password. If you have an older
install that was upgraded you'll need to remove and re-install to get the
new local admin option.

**Comment by tickmc** [comment]
Thanks, Matt - perfect :-)
