### ISSUE TITLE
Does this run in Chromium

### ISSUE THREAD

**Issue by hcarsten** [zebradog/kiosk#17]
Just wondering if the kiosk is tested in Chromium. We are looking into a way to run a kiosk under Rasp PI primary but in development mode on the desktop. So any ideas if and how to make this happen ?

best

**Comment by matt-cook** [comment]
Tested today in the latest Chromium for OSX. Haven't tested on Rasp PI, though I expect it should work just fine. Give it a shot and re-open this issue if you have problems.

**Comment by hcarsten** [comment]
OSx is fine, on Rasp PI we are getting a security problem. The problem is that the Chromium on Rasp PI stucked on V22 or so. I do not have the hw on hand before the weekend, so will test then again and give some feedback. Anyway might be "THE" usecase to have the code running on the 25 bucks machine, or not ?

**Comment by matt-cook** [comment]
Gotcha, will definitely need to be tested with that version.  It's a great use-case. We'd love to see it running on a $25 device.
