### ISSUE TITLE
verify login creditentials, cookies, etc are stored cross-session

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#18]
>  Does the app launch in some sort of incognito mode? As the browser doesn't seem to store my login details (i.e. if there is a website that can remember me, the login screen always appears despite me clicking in "Remeber me")

**Comment by matt-cook** [comment]
Tested as working on OSX 10.10.1, Chrome 40.0.2214.115 (64-bit)

**Comment by tonynz** [comment]
I can help you to test, and also can help you to give you an account on the website that I'm trying. 

Let me know if I can help. 

Thanks!

**Comment by matt-cook** [comment]
No need for account info, I set up a test account. Please do post here if you have a chance to test on a different system.

**Comment by tonynz** [comment]
We only have access to one Chromebox :( . 

I've done a fresh wipe, put it in Kiosk mode, and selected for it to only run in Kiosk mode. 

Just to confirm - Are you trying Klipfolio? 

If so, I'll try to set up a blank account with them, it might have to do with IP restrictions.

**Comment by tonynz** [comment]
Tested with a fresh Klipfolio account. No luck. 

Will trouble shoot myself here also. 

Thanks

**Comment by tonynz** [comment]
Hey Matt, 

Speaking to our developers, and totally novice view from myself, but do you need to declare cookies under permissions in your manifest? 

https://developer.chrome.com/extensions/permissions

Thanks

**Comment by matt-cook** [comment]
@tonynz this has been fixed. added persistant storage in v5.2.2: https://github.com/zebradog/kiosk/commit/16555f655e77f9cbd2c93622666620e1d35c572b

**Comment by matt-cook** [comment]
@kstangel reported still having this issue with LocalStorage and cookies at Bemis. 

The commit above added this line: https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L152 which I believed fixed the issue (documented here: https://developer.chrome.com/apps/tags/webview#partition). @kstangel can you test and confirm that data is not being saved across restarts?

Perhaps changing `persist` to `true` on the background.js script would fix the problem: https://github.com/zebradog/kiosk/blob/master/src/manifest.json#L19 (documentation: https://developer.chrome.com/extensions/event_pages#transition)

There's also a known issue on Android, but probably unrelated?
https://code.google.com/p/chromium/issues/detail?id=479767
https://code.google.com/p/chromium/issues/detail?id=481380

**Comment by kstangel** [comment]
@matt-cook local storage is persistent across restarts of the kiosk application along as chrome does not restart. If chrome closes and restarts between kiosk restarts then local storage is not persistent.

**Comment by kstangel** [comment]
@matt-cook  Tried some of your suggests but localstorage and even using indexedDB did not persist data across chrome restarts. I will have to look at an alternative solution since the application has to remember the previous url in case the application crashes (chrome or kiosk) and restarts based on the watchdog.

**Comment by matt-cook** [comment]
Fixed by 9299bf139543f09643996f17d7f9b6c50350c5e9
