### ISSUE TITLE
Activate Fn keys

### ISSUE THREAD

**Issue by dmougey** [zebradog/kiosk#19]
I have an application who uses the function keys, how I can activate them automatically ?
I can activate them with the Chromebox parameters : Treat top-row keys as function keys, but can I include in your apps ?

**Comment by matt-cook** [comment]
Good question. You're enabling it via Chromebox settings like so?: http://www.chromestory.com/2013/11/get-windows-like-function-keys-chromebook/

We'll look into it if we have some time. If you're on a schedule, email support@zebradog.com and we can work out the details.

**Comment by dmougey** [comment]
I tried this but we lose the configuration after reboot. My ChromeBook is manage with Google Apps Domain. I try to set the policy on Admin console but it don't work with public session.
I explore the way with this policy :  "KeyboardDefaultToFunctionKeys": true. (http://git.chromium.org/gitweb/?p=chromium/src.git;a=blob;f=chrome/test/data/policy/policy_test_cases.json;h=e88cdb91aa2d65b01b4d332956fe1e2ac63860e1;hb=f7f6a6f16b8b53d98040675a95e3aced14cc6a3f)
but I don't know how set up policy.json on apps. May be it's not possible.

**Comment by matt-cook** [comment]
This appears to be a function of the OS and specific application.
