### ISSUE TITLE
Loading Library Children's Catalog - Images on Categories, Series & Chapter Books

### ISSUE THREAD

**Issue by jgivensNAFCPL** [zebradog/kiosk#20]
Hello! Thank you very much for reading this and I hope you can help me out. I'm the network administrator here at the New Albany Floyd County Public Library. I'm considering using Asus Chromeboxes as replacements for our existing Library Catalog PCs (we call them "PACs"). These PCs are only meant for allowing quick access to our library's catalog, to check to see if a book is in, things like that. We have two PAC websites, one for adults/teens, and one for childrens. The adults PAC website seems to work great in your app, I've only done a little bit of testing but so far I haven't had any issues. However, on the children's PAC website inside your app the images won't load. It's very strange. The little square translucent blocks that the images overlay onto loads but the images themselves won't. If you would like to see for yourself the website is http://tlc.nafclibrary.org:8080/kids . The website loads fine in every web browser I have tried, including Google Chrome. 

I really like your app and all the features that you provide, I've tried creating my own Kiosk App but have had no success so far. Any assistance you could possibly provide me is greatly appreciated, thank you!

**Comment by pdrreid** [comment]
(Hi,

Don't have a direct fix for this issue, but am using chromebox / zebradog for library OPACs too, and facing similar issues (would like to make a local app too, for instance). We have cover images pulled in to search results to our OPAC by ISBN (sirsi dynix symphony), but that's from a third party called Syndetics (yours looked like they came from your own servers) , and ours display fine when kiosked.  

Anyway, if you want to contact me outside of Github, my email is p.reid2@bathspa.ac.uk, it would be good to hear any progress you make and share experience with this. Peter)

**Comment by matt-cook** [comment]
@jgivensNAFCPL or @pdrreid are you still seeing this issue? Just tested with latest version (v5.3.0) and it appears correctly: 

![screen shot 2015-05-27 at 12 53 46 pm](https://cloud.githubusercontent.com/assets/626516/7843488/8b817352-046f-11e5-88c1-643dd9f05850.png)

I'll re-open if it is still occurring. Very cute app!
