### ISSUE TITLE
Chrome App store has old version

### ISSUE THREAD

**Issue by Doltknuckle** [zebradog/kiosk#22]
I look at the Chrome Apps store and this is still on version 5.2.0

I really want to use the local admin mode. Could someone update the Chrome app package?

**Comment by matt-cook** [comment]
We're on it! Sorry documentation is unclear: 5.3.0 is still in progress. I've updated the readme to reflect this (and clarify our support structure). If you need it on a timeline: send us and email and we'll expedite the feature for you.

**Comment by Doltknuckle** [comment]
I didn't realize 5.3.0 wasn't ready. Looking forward to seeing it when it is released.
