### ISSUE TITLE
Define remote config file spec and add remote config feature

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#23]
Allow centralized management of multiple devices, push notifications to send command and update settings centrally. Would also function as a work-around for #14 

Likely will use GCM: https://developer.chrome.com/apps/cloudMessaging

**Comment by rkralston** [comment]
This web server looks interesting:

https://github.com/kzahel/web-server-chrome

**Comment by matt-cook** [comment]
@rkralston we're looking at using this solution for #9. This specific feature will be implemented by defining a spec (likely REST/JSON based) for remote config files and adding a field in the Kiosk admin to specify and arbitrary remote server.

Not GCM as previously suggested.

**Comment by matt-cook** [comment]
Editing this feature to simple remote config spec, full management website will be an instance of Westminster: https://github.com/zebradog/westminster and beyond the scope of this app.

**Comment by matt-cook** [comment]
This will be handled via policy files instead of remote config: https://github.com/zebradog/kiosk/issues/37
