### ISSUE TITLE
app doesn't reload if chrome isn't running

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#27]
If only app is open, when it reloads it closes entirely since Chrome process has ended. Probably solved by adding 'background' optionally.

**Comment by matt-cook** [comment]
This applies to desktop OS, on ChromeOS it works correctly.

**Comment by matt-cook** [comment]
https://developer.chrome.com/extensions/declare_permissions#background

**Comment by kzahel** [comment]
I didn't get a chance to test this, and am not actually sure how this interacts with windows vs chromeos vs osx etc.

On windows I could see how if you close the kiosk app, the remote administration page no longer works, including the restart button, of course.

It believe it would be possible to remove the persistent:false from the background manifest, and then have the remote administration still working even if the kiosk window is closed.

Not sure if this matters to anyone though

**Comment by matt-cook** [comment]
Fixed by 21fa22517c3415a237821e5021e779ba4dd89496
