### ISSUE TITLE
Add 5.3.4 to Releases Tab

### ISSUE THREAD

**Issue by xd1936** [zebradog/kiosk#34]
Love this Chrome app! Please make the latest version available in the [releases section](https://github.com/zebradog/kiosk/releases) here on Github :)

**Comment by matt-cook** [comment]
Thanks! Thanks for the note... we've been slacking on keeping that page up-to-date.

**Comment by xd1936** [comment]
Of course! Thanks for all of your hard work!

**Comment by matt-cook** [comment]
Done!
