### ISSUE TITLE
How to disable right click mouse in kiosk mode

### ISSUE THREAD

**Issue by MichalMusial** [zebradog/kiosk#35]
Hi Matt,
I have a touch screen monitor.when holding me finger on the image (see Annex). a touch overlay options can't turn it off. I use Windows Embedded 8.1 Industry Pro. in registers systems  I have not found anything that could disable. could you help me?
![right click in pict](https://cloud.githubusercontent.com/assets/13250949/8590309/99390e70-261f-11e5-943b-73c74cb4a672.jpg)

Thanks Michal

**Comment by matt-cook** [comment]
Hi @MichalMusial 

We generally do this by adding:
```
$(document).bind("contextmenu",function(e){
      return false;
    });
```
to our application code, as well as `window.ondragstart = function(){return false};` to disable image dragging. 

Might be useful to simply have this as a feature of the Kiosk app, so I've created another issue to track that: https://github.com/zebradog/kiosk/issues/36
