### ISSUE TITLE
Add option to disable extra browser cursor features

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#36]
Probably optionally from the setup page

```
window.ondragstart = function(){return false};
    $(document).bind("contextmenu",function(e){
      return false;
    });
```

**Comment by MichalMusial** [comment]
Hi Matt,
Thank you for your response.
Please tell me, will be available the new version 5.3.5? :) 
which will be blocked right mouse button?
Michal

**Comment by matt-cook** [comment]
```
$(document).bind("contextmenu",function(e){
      return false;
    });
``` 
...disabled the right click menu. I can't make any garantuees on functionality for the next version, but this is a pretty simple and useful adjustment so it's pretty likely.

**Comment by MichalMusial** [comment]
Matt sorry to bother you, 
and you tell me when it will be a new version? :P
Then quickly I check and I'll let you know if it works :D

**Comment by matt-cook** [comment]
No guarantee on that either, sorry. I'll close this issue once it's added. If you need it on a specific schedule send us an email: support@zebradog.com for a quote.

**Comment by matt-cook** [comment]
Probably will also hide the cursor and disable text selection via:
https://developer.chrome.com/apps/tags/webview#type-InjectDetails

```
body,html{
  cursor:none;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
*{
  -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
