### ISSUE TITLE
remote schedule server not working

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#43]
As reported:

>This feature is not working for me, maybe it's a bug as I understand it is fresh out of development.
>
>This URL we are pulling from is publically accessible, but from our testing it doesn't seem to utilize it and always displays the default URL. 
>
>https://www.ripleys.com/playorlando/displays/1-gallery-display.json
>
>Any obvious errors in the JSON file, or is it conflicting with other configured settings within the app?
>
>Thanks for the great plugin!

**Comment by matt-cook** [comment]
Appears to be functioning correctly. Provided sample has a start date in January.

**Comment by nathang21** [comment]
Maybe I misunderstood what you meant, but nothing appears wrong with our JSON file.

Our end date is 10 years in the future, and our start date is in the past (January). You said " Provided .json file had a start date in January of this year, so won't be shown yet." But its way past January of this year, so what am i missing?

Thanks for getting back to me, if this could be re-opened we would greatly appreciate it.

**Comment by matt-cook** [comment]
Ah, yes. I had January as last year in my mind, for whatever reason.. yikes. Re-opened and investigating.

**Comment by matt-cook** [comment]
![cors-error](https://cloud.githubusercontent.com/assets/626516/9335822/efaeeef0-459b-11e5-8805-92b5f52bd403.png)

CORS headers are required on the schedule server (or alternatively, you can use this plugin: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en-US client-side).
