### ISSUE TITLE
add support for push messaging schedule server

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#45]
For immediately updating schedule versus polling.

**Comment by kzahel** [comment]
ah, here you mean chrome.gcm, right?
I have been working with it recently and am developing very nice python XMPP google cloud messaging server

**Comment by kzahel** [comment]
Isn't this a feature of the management console, though? or is this for users who don't have enterprise managed devices?

**Comment by matt-cook** [comment]
Originally we were thinking about rolling-our-own management system. Agreed that this would be better done through management console or policy update. Closing this issue since it will be handled by: https://github.com/zebradog/kiosk/issues/37

**Comment by trevoriancox** [comment]
We are planning to add GCM. In our case, we have managed Windows computers that are set up initially using group policy, but our system for managing the content of the kiosks is independent of that.

**Comment by kzahel** [comment]
@trevoriancox that makes sense. The GCM docs are a bit confusing with FCM actually being the suggested way to use chrome.gcm now. Feel free to reach out to me if you run into any problems.
