### ISSUE TITLE
Javascript Carousel Banner Won't show in Kiosk

### ISSUE THREAD

**Issue by kgreg10** [zebradog/kiosk#48]
Hello,

I have developed a simple web page to show a rotating banner or carousel banner. The page works in my chrome browser, but does not work in kiosk app. Or maybe it is but the css is not working. Any ideas?

**Comment by matt-cook** [comment]
Can you share a link or sample code so we can reproduce the issue? Definitely something we'd like to look into. The use case you describe is exactly the target use for the application.

**Comment by kgreg10** [comment]
Yes, sorry. First time user of Github. Here is the link to the page. It is very simple: http://www.centraltech.edu/hall_of_fame/hall_of_fame.html

**Comment by matt-cook** [comment]
Thanks. The second slide (http://www.centraltech.edu/hall_of_fame/images/grizzly_bear.jpg) is giving me a 404. Aside from that, it's working both in Chrome and via the Kiosk app here. Initial slide loads, then starts transiting back and forth after a short delay.

Are you using version 5.4.0 of the app? Can you also go to chrome://chrome/ and let me know what version you're using? Operating system version would also be helpful.

**Comment by kgreg10** [comment]
Yes, I knew the grizzly bear picture was not there. I will upload a picture so that we can see it move. 

Kiosk App version is: 5.4.0
Chrome version: 44.0.2403.157 (64-bit)
OS version: Yosemite 10.10.5

**Comment by kgreg10** [comment]
Also, just so you know what I am seeing on my end. When I launch the Kiosk app it opens I paste the url in and then when it starts, all I see is a blank white screen.

**Comment by matt-cook** [comment]
Interesting. I'm running exactly the same configuration here and it is working correctly. Do you have an additional settings applied in the Kiosk setup page? (hidden cursor, remote admin, etc.). Do you have access to any other machines to test on?

**Comment by kgreg10** [comment]
I have "Hide Cursur", "Disable Context Menu", and Local Administration all checked. I also have Inactivity Reset and Daily Restart checked as well. 

Yes, I have a laptop that I will try it on and I will let you know what I see.

**Comment by kgreg10** [comment]
Ok, it works perfectly on my macbook. I'm really confused why it isn't working on my iMac.

**Comment by matt-cook** [comment]
I'm also curious. This is the first we've heard of this type of problem. Are you familiar with loading unpacked chrome extensions and/or using Chrome Developer Tools? You can download the unpacked extension here (under /src): https://github.com/zebradog/kiosk/archive/5.4.0.zip

It may be useful to run that, then inspect the background or browser.html page and see if you can track down the issue.

**Comment by kgreg10** [comment]
I may have figured out the problem. Our IT department has a slow cache refresh here for our network so I think it may be that it is not updating as quickly as it does when I push it to our online hosting servers.

Could that be the problem?

**Comment by matt-cook** [comment]
Sounds like it could be. Strange it worked on one computer and not on another. I'll close this for now. Please comment if you continue to see it on a production machine.
