### ISSUE TITLE
Add web page load error handling?

### ISSUE THREAD

**Issue by trevoriancox** [zebradog/kiosk#50]
I don't see this feature in the code... Is any one is working on it already?

Issue:
- kiosk code invokes window.location.reload(), or is doing initial load,
- server is down or there is a network connection problem
- Chrome shows an error page
- plugin should retry...

**Comment by matt-cook** [comment]
If I understand correctly, in addition to the existing unresponsive/abort handling (https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L155), you're requesting the application reset on 400/500 HTTP errors as well?

So setting content URL to `http://httpstat.us/500` would continuously reload (as desired).

**Comment by trevoriancox** [comment]
Thanks @matt-cook! No, I just didn't see the existing unresponsive/abort handling in the code, sorry,. and wanted to make sure that existed. :) Since you've written up a new enhancement description I'll leave it to you if you want to close this "issue".

**Comment by matt-cook** [comment]
Additional follow up work addressed in #72
