### ISSUE TITLE
Set focus on input text box, for scanner input, with no mouse or keyboard attached.

### ISSUE THREAD

**Issue by apaGitHub** [zebradog/kiosk#51]
Currently, when the content URL is loaded, focus is not set until tab key is pressed, or on mouse click.
When same content URL is loaded in Chrome, focus is immediately established.

**Comment by matt-cook** [comment]
We won't be adding content-specific functionality to the kiosk app (such as automatically selecting a specific form element on page load). This should be handled at the application level via javascript: http://stackoverflow.com/questions/17500704/javascript-set-focus-to-html-form-element

**Comment by matt-cook** [comment]
Reported again related to this bug: https://code.google.com/p/chromium/issues/detail?id=501062

> Okay, so the reason that this is not working is because in order for anything to focus within a webview (including from autofocus), the webview itself must be focused as well. Until recently there was no way to reliably focus a webview because of a related bug ( issue 503832 ), but that is fixed now.
 

> Now,  if you want to be able to guarantee that autofocus will work when navigating to a page, you should both navigate AND focus the webview. For example, you can use: "webview.src = 'some URL'; webview.focus()". I've tested that and it works for the example link provided with this bug.

May simply be a matter of calling `webview.focus()` after loading page.
