### ISSUE TITLE
 Links not working

### ISSUE THREAD

**Issue by jsarmie** [zebradog/kiosk#55]
I'm using http://www.presidentscup.com.  When scrolling to the bottom and clicking on the PGA Tour link in the bottom menu, it is not working.  The link works in chrome and also when using the --kiosk flag.

**Comment by matt-cook** [comment]
This is because pop-ups (and new tabs, which is the case here) are currently blocked by the app. This a known request: https://github.com/zebradog/kiosk/issues/6

It's not currently a high priority for development since we don't have any billable projects requiring this feature.
