### ISSUE TITLE
File Brouser

### ISSUE THREAD

**Issue by eredeli** [zebradog/kiosk#58]
Hi, Help!!! :) i need Make the app Brose:  \\folder or \\file
app is for http:// brose only... 
Can u?

THANKS!!!!

**Comment by matt-cook** [comment]
Thanks for the request. Currently since local files are supported, we recommend using a local web server  like Mongoose (https://github.com/cesanta/mongoose) or XAMPP, etc.

Long term, we would like to add this feature. This issue is being tracked here: https://github.com/zebradog/kiosk/issues/9

**Comment by eredeli** [comment]
wow :) greaaat! cool! Thanks! Hope this will be added soon...
