### ISSUE TITLE
Swipe

### ISSUE THREAD

**Issue by johnnydevs** [zebradog/kiosk#59]
I am using a Dell s2240T touch screen monitor.

When I launch the Kiosk app I can't swipe between pages as I can do in Chrome. Am I doing something wrong?

I have only enable 'hide cursor' in settings.

Thanks

**Comment by matt-cook** [comment]
> swipe between pages

To navigate through your history to previous/next pages? or other tabs? or a swipe event handled by your application? (the latter should definitely be supported).

**Comment by johnnydevs** [comment]
Thanks for the reply. I mean to swipe between my history previous/next pages. Same functionality as the back/forward button.

This doesn't work. Any suggestions?

I am using this to browser the internet, nothing advamced.

Thanks

**Comment by matt-cook** [comment]
Currently next/back browsing isn't integrated into Kiosk. You'd need to implement this at the application level. Kiosk is currently designed to be a fully functional browser. As-is it's tailored for launching a specific URL and any functionality is managed inside the application.

Long term, we have been getting requests for additional browser functionality but it doesn't currently fit the use-case for any of our billable projects, so it's unlikely to make it into the app unless we find a sponsor for those features.

**Comment by matt-cook** [comment]
Since this is a commonly requested item we're tracking it here: #66
