### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by heaversm** [zebradog/kiosk#61]
Hi - I'm trying to enter admin mode and I don't remember ever having set up a username / password. Is there a default? If not, is there a way to recover password?

**Comment by matt-cook** [comment]
Nope, no default password. If you have local administration turned on, it forces you to select a password on installation (unless you've found a bug...)

You'll need to re-install the application (or tell the device to forget user data and restart) to reset the password, this will also clear all the other kiosk app settings unfortunately.

**Comment by Wasabiboy** [comment]
Sorry to wake this question again. Ok, I set a password, but geez can't remember the username? Think I left it default but Admin isn;t is etc? What would be the default user name?

**Comment by Wasabiboy** [comment]
HA...solved it... Not Admin, case sensitive admin!!! Thanks anyway
