### ISSUE TITLE
Deployment without manual configuration (Linux/Windows)

### ISSUE THREAD

**Issue by trevoriancox** [zebradog/kiosk#67]
I need to automatically deploy to many computers, each one with a unique URL that includes an identifier of the computer/location. It seems that a Chrome App cannot be passed any identity information from the command line or elsewhere, but an Extension could detect the URL passed on the command line. 

Kiosk cannot be converted to an Extension; in trying to do so we see these warnings:

- 'kiosk_enabled' is only allowed for packaged apps, but this is a extension.
- 'sockets' is only allowed for packaged apps, but this is a extension.
- 'app.window.alwaysOnTop' is only allowed for packaged apps, but this is a extension.
- 'fileSystem' is only allowed for packaged apps, but this is a extension.
- 'fileSystem.directory' is only allowed for packaged apps, but this is a extension.
- 'webview' is only allowed for packaged apps, but this is a extension.
- 'system.network' is only allowed for packaged apps, but this is a extension.
- 'audioCapture' is only allowed for packaged apps, but this is a extension.
- 'videoCapture' is only allowed for packaged apps, but this is a extension.

Perhaps the solution is a "Kiosk Launcher Extension" that gets the URL, and then Kiosk App uses message passing to detect the extension and get the configuration from the extension if available.

I'm working on this now so any feedback would be invaluable...

![](https://api.bountysource.com/badge/issue?issue_id=28362501)

**Comment by trevoriancox** [comment]
I now have this working, details to follow shortly. If no one here is interested in merging this feature, I will have to publish my own fork.

**Comment by matt-cook** [comment]
@trevoriancox thanks for feature request / work. We have similar use cases and were planning on addressing via config upload in Chrome Management Console: https://github.com/zebradog/kiosk/issues/37

If you've already solved it via an extension we're definitely open to reviewing and merging, just submit a pull request. No worries if you prefer to keep your own fork either.

**Comment by trevoriancox** [comment]
Good to hear, @matt-cook. #37  and the Chrome Management Console are focused on Chrome devices, while our use case is for Windows devices. And my solution doesn't require extra licenses or as much complexity.

**Comment by bfleishman** [comment]
I'd love to see more details on this solution as we would like to centrally manage our KIOSK devices without the cost and limitations of the Chrome Management Console. Can you provide more information?

**Comment by matt-cook** [comment]
Makes sense re. Windows/non-chromebox devices. We run into the same thing here. We're also looking at defining a spec and adding the ability to ping a remote server for config file: https://github.com/zebradog/kiosk/issues/23 Similar to how the scheduling server feature currently works. Might not solve your use case exactly (requires a remote http server and access to it), but related.

**Comment by trevoriancox** [comment]
With #23, how would the config server identify each kiosk? Or was that not a requirement?

**Comment by matt-cook** [comment]
We've been handling for scheduling this by simply specifying a url parameter, ex: `http://www.domain.com/my-config-handler?id=xyz`

Would like to look into better auth methods, since this only works for insecure data.. but that's how the initial implementation will work.

**Comment by bfleishman** [comment]
Can you provide an example of how your schedule page is formatted? Thanks.

Best Regards,
Brian Fleishman

|\ Need Immediate Help? Email the support Desk: support@jaydien.com<mailto:support@jaydien.com> /|

**Comment by matt-cook** [comment]
Sure, it's in the readme: https://github.com/zebradog/kiosk#remote-schedule-server

**Comment by trevoriancox** [comment]
The solution isn't as elegant as hoped, and has only been tested on Windows. The extension is now published at:

- https://chrome.google.com/webstore/detail/gafgnggdglmjplpklcfhcgfaeehecepg

and is on github at:

- https://github.com/appazur/kiosk-launcher

The changes to Kiosk are very simple, and can be seen in this fork:

- https://github.com/appazur/kiosk

Please respond if there is interest in merging, otherwise I will publish this fork separately.

**Comment by matt-cook** [comment]
Thanks for the hard work on this workaround. We feel the best method would be adding the ability to specify settings via a policy file #37 (http://www.chromium.org/administrators/configuring-policy-for-extensions) so we'll be working on that (versus simply adding parameters to a shortcut).
