### ISSUE TITLE
Use Kiosk Mode on Chromebox not working

### ISSUE THREAD

**Issue by bert1468** [zebradog/kiosk#69]
I am trying to use the chromebox in Kiosk mode autolaunch the Kiosk App to display a webpage and it does not work.  When I click save in the app it restarts the chromebox and it brings me to the setup page again.    Am I missing something?  Can I not use the Kiosk app in the Kiosk mode for a managed chromebox?
 
thanks

**Comment by matt-cook** [comment]
You definitely can use it in Kiosk mode, that's our recommended solution. It sounds like you may have the `forget user data on logout` (I don't recall the exact wording off-hand) setting turned on. This will need to be turned off to preserve the app settings across restarts. 

If this settings is off and you're still having trouble, please let us know.

**Comment by bert1468** [comment]
Perfect.  That worked.

Thanks much
