### ISSUE TITLE
Schedule JSON

### ISSUE THREAD

**Issue by akeilox** [zebradog/kiosk#76]
I have followed the instructions and installed the Allow origin extension to chrome from
https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en-US

I have a target URL, https://domain.com/kiosk-schedule/ where it returns a valid JSON (verified with JSON checker) as per below (2 schedules);

{"schedule":{"Value":{"items":[{"content":"https://domain.com/kiosk/a1/","end":"Tue Dec 22 2015 00:22:25 GMT+08:00","start":"Sat Dec 19 2015 00:21:20 GMT+08:00"},{"content":"https://domain.com/kiosk/a2/","end":"Thu Dec 24 2015 00:22:20 GMT+08:00","start":"Tue Dec 22 2015 03:32:10 GMT+08:00"}]}}}

Is there more to it, beside enabling it on Kiosk app with url https://domain.com/kiosk-schedule/ at 5 min interval?

It doesnt seem to move from one to another (a1 to a2 url) , tried playing with timings etc.

would appreciate if someone can shed light.

**Comment by sommestad** [comment]
+1

**Comment by akeilox** [comment]
I have re-visited it again after seeing the +1, as previously I had the impression I might be doing something wrong.

It still doesnt seem to work, given a valid JSON string as specified in the instructions.

The chrome extension stated, allow-origin is already installed along with the kiosk extension.
The URL given to fetch the JSON schedule works, json returned with correct content-type when page is requested. 

Yet I dont know how to debug further from this point forward to see why its not working.
Where can I look for any debugging information?

It would be great if someone can shed light on this, as I really wish to get this up and running.

**Comment by alexvandenbos** [comment]
I encountered the somewhat the same problem. I have a valid JSON string as specified and installed allow origin along with the kiosk extendsion.

Yet, at a 5 min interval as you described, it doesn't respond to my JSON file (at all). How can i debug this, or test this any further? I hope to hear from you

**Comment by akeilox** [comment]
@alexvandenbos I didnt get it to work, having checked json, content type, cross domain extension.
It seems the url is not being polled even, and I dont know where to look for debugging information.

It would be great if the developers can chip in on this.

**Comment by mattzuba** [comment]
Not sure if it helps anyone, but I noticed that Chrome was caching my schedule.json file (200 OK (from cache)), so it wasn't even hitting my server to get a new copy.  I set some headers to prevent caching and cleared all local caches and now it always pulls a fresh copy of the schedule and updates like it should.

**Comment by kzahel** [comment]
The fetcher should probably append a random query parameter to disable the caching

**Comment by matt-cook** [comment]
While @mattzuba's solution seems the most correct, that's a good idea @kzahel: it would probably be the easiest solution.

**Comment by matt-cook** [comment]
This has been fixed: 9637effd785b8bf9cc53394b5e352d893b583d66 and will be available in version 5.7.2 in the web store later today.
