### ISSUE TITLE
Esc

### ISSUE THREAD

**Issue by Twiggled** [zebradog/kiosk#77]
Is there any way to stop it from exiting full screen mode when you press esc on a keyboard.
We use linux systems and trying to use this so our staff only have access to our website and crm system.

But if they can just press esc then it defeats the purpose. Tried it on Windows 7 Chrome.
Thanks in advance is a really good app.

**Comment by matt-cook** [comment]
Thanks for the report. Similar to alt-f4, ctrl+alt+delete, etc we don't currently have a way to block system keystrokes. There are registry hacks, etc. that can be applied on OSX/Windows/Linux though our recommended solution for "locked-down" kiosks is using a Chrome OS device in "Kiosk" mode.

**Comment by matt-cook** [comment]
@Twiggled Google added the ability to block this recently, so it's been fixed in version 5.5.2 which is now published in the web store. Thanks for reporting!

**Comment by Jamman** [comment]
I can't find this ability in the latest version - can you confirm where this is configured?
