### ISSUE TITLE
how to launch kiosk automatically at system startup on mac osx

### ISSUE THREAD

**Issue by heaversm** [zebradog/kiosk#78]
Hi - I want to launch kiosk when my mac starts. I tried a few things:

I've gone to system preferences > accounts > login items and added Kiosk (User > Applications > Chrome Apps > Kiosk) but it won't launch. I've tried also adding the chrome app launcher and chrome itself as login items but that doesn't work either.

I do have an automator application running at startup which executes a few node.js commands from a bash script, so maybe I could do it that way, but I'm not sure how.

If I go to the application icon and get info, I can see it says: 

`Default afhcomalholahplbjhnmahkoekoijban.app` under name and extension, and its location is /Users/mikeheavers/Applications/Chrome Apps.localized but if I attempt to run:

```
open -a Default /Users/mikeheavers/Applications/Chrome\ Apps.localized/afhcomalholahplbjhnmahkoekoijban.app
```

from terminal it says that the file doesn't exist.

**Comment by matt-cook** [comment]
I was able to do this on OSX 10.10.5 by navigating to [chrome://apps](chrome://apps) and right-clicking on Kiosk to create an application shortcut:

![screen shot 2016-02-09 at 9 01 53 am](https://cloud.githubusercontent.com/assets/626516/12924276/e0dcb292-cf1e-11e5-9407-07478c0f9f16.png)

Then adding the application to login items via System Preferences -> Users & Groups correctly started the application on startup.
