### ISSUE TITLE
preserving cookies

### ISSUE THREAD

**Issue by heaversm** [zebradog/kiosk#80]
Hi - I have a simple cookie that I set which needs to preserve the device ID for my various kiosks running this app. However, it seems that the app might not be allowing me to store the cookie (or might be clearing it out). 

Can you verify whether or not the app allows the storage of cookies? And if so, how and when are those cookies reset?

Does Kiosk's cookies operate separately from the Chrome browser (meaning, if I set a cookie in Chrome, will it be readable in Kiosk?)

Thanks!

Mike

**Comment by matt-cook** [comment]
Cookies are preserved (or should be! let us know if that's not the case for you) within the Kiosk app. However, they are not shared with the standard Chrome browser.

**Comment by matt-cook** [comment]
Feel free to re-open if you're still having trouble.

**Comment by matt-cook** [comment]
After conversation with @kstangel this is a known issue (dupe. of: #18) which has been fixed: https://github.com/zebradog/kiosk/pull/68 though not publish in the app store yet.
