### ISSUE TITLE
Full screen for YT video doesn't work

### ISSUE THREAD

**Issue by fxbodin** [zebradog/kiosk#82]
_Sorry for crossposting on Google web store, I understand you prefer Github..._

Hi!

First, thanks for your amazing app that is very convenient in many uses cases.
However I face an issue on a particular project.

My web app displays selected youtube videos. Everything goes fine except that the video fullscreen function doesn't work. I can see the screen blinking, like if it "tried" to display the full screen video, then fails. Tested likewise on the latest version of Chrome Windows 7 and 10, and OSX. Tested also on the Youtube homepage and same behavior.

Is this a desired behavior or a bug?

The URL : http://www.aquitaine-cap-metiers.fr/videotheque

Thanks in advance for your answer.
Best regards from Bordeaux-France
\-- 
@fxbodin

**Comment by matt-cook** [comment]
Thanks for the bug report. We'll be looking into this for a patch release at the end of the month.

**Comment by fxbodin** [comment]
Hi Matt.

Glad to have pointed a bug out.

I'd be fine to get an advice when the patch is released, so that I can 
revert my kiosks to your plugin.

Have a nice day.
-- 
from Bordeaux - France
@fxbodin
