### ISSUE TITLE
Multi-screen support

### ISSUE THREAD

**Issue by seantrace** [zebradog/kiosk#84]
Very useful app, but is there a way to control which screen the kiosk mode chrome is displayed on?

**Comment by matt-cook** [comment]
Thanks Sean. Currently, no. This has been on our radar for a while:

https://github.com/zebradog/kiosk/issues/2

Hasn't been added to a specific development milestone yet, but if you'd like to prioritize you can place a bounty here: https://www.bountysource.com/issues/2677908-add-multi-display-support
