### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by eredeli** [zebradog/kiosk#93]
Have problem on Google OS - Web page edited, but not refreshed (shows old version web), how i can refresh? nothing helps :( thanks

**Comment by kstangel** [comment]
It sounds like a caching issue? 

I have had success with doing one of these three things:

- Clearing cache on chrome browser
- Uninstalling and reinstalling the Kiosk App
- I had success with installing and running an extension that removes all cache data (see below). It seems to remove the app cache for the extension. 
https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn

**Comment by matt-cook** [comment]
Thanks Kyle. Agreed. There was a PR to address this that will be published in the next update (5.6.0): https://github.com/zebradog/kiosk/pull/73

**Comment by eredeli** [comment]
Thanks, but i allready done that! :) not worked.. still have problem.
