### ISSUE TITLE
How to run a webapp offline in kiosk app.

### ISSUE THREAD

**Issue by lhadji** [zebradog/kiosk#95]
We have this issue that when the network connection is down, kiosk app shows a white blank page instead of showing offline mode.

**Comment by matt-cook** [comment]
You can either run your application entirely locally for the "serve local content" option or you'll need to update your hosted application to support running offline, probably via [ServiceWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
